name: 'Run quickstart'
description: 'Runs quickstart docker image'
inputs:
  tag:
    description: "Image tag of quickstart image to use"
    required: true
    default: "latest"
  artifact:
    description: "Artifact to collect image from"
    type: string
    default: ""
  image:
    description: "Image for the quickstart image to use"
    default: ""
  enable:
    description: "Services to enable"
    default: "core,horizon,rpc"
  network:
    description: "Network to run"
    default: "local"
  protocol_version:
    description: "Protocol version to run for 'local' network only (leave blank for default for image)"
    default: ""
  enable_logs:
    description: "Boolean flag enabling the logs"
    default: "true"
  health_interval:
    description: "Time between running the check (in seconds)"
    default: "10"
  health_timeout:
    description: "Maximum time to allow one check to run (in seconds)"
    default: "5"
  health_retries:
    description: "Consecutive failures needed to report unhealthy"
    default: "50"
runs:
  using: "composite"
  steps:
    - name: Setup Colima and Docker (macOS only)
      if: runner.os == 'macos'
      shell: bash
      run: |
        brew update
        brew install colima docker
        CPU_COUNT=$(sysctl -n hw.ncpu)
        TOTAL_MEMORY=$(sysctl hw.memsize | awk '{print $2/1024/1024/1024}')
        MEMORY=$(awk "BEGIN {printf \"%.0f\", $TOTAL_MEMORY * 0.75}")
        colima start --arch x86_64 --vm-type=vz --mount-type=virtiofs --cpu $CPU_COUNT --memory $MEMORY --network-address
        export DOCKER_HOST=unix:///Users/runner/.colima/default/docker.sock
        echo "DOCKER_HOST=unix:///Users/runner/.colima/default/docker.sock" >> $GITHUB_ENV

    - if: inputs.artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: /tmp/

    - if: inputs.artifact
      run: docker load -i /tmp/image
      shell: bash

    - run: >
        docker run -d --name stellar 
        -p 8000:8000 
        -p 11626:11626 
        -p 11726:11726 
        -p 11826:11826 
        -e ENABLE_LOGS="${{ inputs.enable_logs }}"
        -e ENABLE="${{ inputs.enable }}"
        -e NETWORK="${{ inputs.network }}" 
        -e PROTOCOL_VERSION="${{ inputs.protocol_version }}" 
        --health-cmd "curl --no-progress-meter -X POST -H 'Content-Type: application/json' -d 
        '{\"jsonrpc\": \"2.0\", \"id\": 1, \"method\": \"getHealth\"}' 'http://localhost:8000/rpc' 
        | grep 'healthy'
        && curl --no-progress-meter \"http://localhost:8000/friendbot\" | 
        grep '\"invalid_field\": \"addr\"'" 
        --health-interval ${{ inputs.health_interval }}s 
        --health-timeout ${{ inputs.health_timeout }}s 
        --health-retries ${{ inputs.health_retries }} 
        ${{ inputs.image || (inputs.artifact && 'quickstart' || 'docker.io/stellar/quickstart') }}:${{ inputs.tag }}
      shell: bash

    - name: "Wait for container to be healthy"
      run: |
        i=0
        while true; do
          status=`docker inspect -f {{.State.Health.Status}} stellar`
          echo "stellar image status: $status"
          if [ "$status" == "healthy" ]; then
            break
          fi
          sleep 1;
          i=$((i + 1))
          if (( $i > 300 )); then
            echo "stellar image is slow to start, printing logs:"
            i=$((i - 300))
            docker logs stellar
          fi
        done;
      shell: bash
