name: 'Run quickstart'
description: 'Runs quickstart docker image'
inputs:
  tag:
    description: "Image tag of quickstart image to use"
    required: true
    default: "latest"
  artifact:
    description: "Artifact to collect image from"
    type: string
    default: ""
  image:
    description: "Image for the quickstart image to use"
    default: ""
  enable:
    description: "Services to enable"
    default: "core,horizon,rpc"
  network:
    description: "Network to run"
    default: "local"
  protocol_version:
    description: "Protocol version to run for 'local' network only (leave blank for default for image)"
    default: ""
  enable_logs:
    description: "Boolean flag enabling the logs"
    default: "true"
  health_interval:
    description: "Time between running the check (in seconds)"
    default: "10"
  health_timeout:
    description: "Maximum time to allow one check to run (in seconds)"
    default: "5"
  health_retries:
    description: "Consecutive failures needed to report unhealthy"
    default: "50"
runs:
  using: "composite"
  steps:
    - name: Set up Colima for macOS
      if: runner.os == 'macOS'
      run: |
          brew install colima docker
          # Get available resources (GitHub Actions macOS runners typically have 4-6 CPUs, 14GB RAM)
          CPU_COUNT=$(sysctl -n hw.ncpu)
          MEMORY_GB=$(sysctl hw.memsize | awk '{printf "%.0f", $2/1024/1024/1024}')
          # Use 75% of available memory to leave some headroom for the host
          MEMORY_LIMIT=$((MEMORY_GB * 3 / 4))
          echo "Available CPUs: $CPU_COUNT, Memory: ${MEMORY_GB}GB, Allocating: ${MEMORY_LIMIT}GB to Colima"
          # Start Colima with explicit resource limits
          colima start --cpu $CPU_COUNT --memory $MEMORY_LIMIT --vm-type=vz --mount-type=virtiofs || {
            echo "Colima start failed, checking status..."
            colima status || true
            exit 1
          }
          # Monitor Colima resource usage
          echo "Colima VM status:"
          colima status
          echo "DOCKER_HOST=unix://$HOME/.colima/default/docker.sock" >> $GITHUB_ENV
      shell: bash

    - name: Set up Docker
      if: runner.os != 'macOS'
      uses: docker/setup-docker-action@efe9e3891a4f7307e689f2100b33a155b900a608 # v4.5.0

    - if: inputs.artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: /tmp/

    - if: inputs.artifact
      run: docker load -i /tmp/image
      shell: bash

    - run: >
        docker run -d --name stellar 
        -p 8000:8000 
        -p 11626:11626 
        -p 11726:11726 
        -p 11826:11826 
        -e ENABLE_LOGS="${{ inputs.enable_logs }}"
        -e ENABLE="${{ inputs.enable }}"
        -e NETWORK="${{ inputs.network }}" 
        -e PROTOCOL_VERSION="${{ inputs.protocol_version }}" 
        --health-cmd "curl --no-progress-meter -X POST -H 'Content-Type: application/json' -d 
        '{\"jsonrpc\": \"2.0\", \"id\": 1, \"method\": \"getHealth\"}' 'http://localhost:8000/rpc' 
        | grep 'healthy'
        && curl --no-progress-meter \"http://localhost:8000/friendbot\" | 
        grep '\"invalid_field\": \"addr\"'" 
        --health-interval ${{ inputs.health_interval }}s 
        --health-timeout ${{ inputs.health_timeout }}s 
        --health-retries ${{ inputs.health_retries }} 
        ${{ inputs.image || (inputs.artifact && 'quickstart' || 'docker.io/stellar/quickstart') }}:${{ inputs.tag }}
      shell: bash

    - name: "Wait for container to be healthy"
      run: |
        i=0
        while true; do
          status=`docker inspect -f {{.State.Health.Status}} stellar`
          echo "stellar image status: $status"
          if [ "$status" == "healthy" ]; then
            break
          fi
          sleep 1;
          i=$((i + 1))
          if (( $i > 300 )); then
            echo "stellar image is slow to start, printing logs:"
            i=$((i - 300))
            docker logs stellar
          fi
        done;
      shell: bash
