FROM ubuntu:20.04

MAINTAINER Bartek Nowotarski <bartek@stellar.org>

EXPOSE 5432
EXPOSE 8000
EXPOSE 6060
EXPOSE 11625
EXPOSE 11626

ADD dependencies /
RUN ["chmod", "+x", "dependencies"]
RUN /dependencies

# Requires building the testing image of stellar-core. E.g.:
# docker build git://github.com/stellar/stellar-core-experimental-cap21and40#cap21and40 -e CONFIGURE_FLAGS='--disable-tests' -f docker/Dockerfile.testing -t stellar/stellar-core:testing
RUN apt-get -y install libunwind8 postgresql curl sqlite iproute2 libc++abi1-10 libc++1-10
COPY --from=stellar/stellar-core:testing /usr/local/bin/stellar-core /usr/bin/stellar-core

# Requires building the dev image of stellar-horizon. E.g.:
# docker build git://github.com/stellar/go#cap21and40 -f services/horizon/docker/Dockerfile.dev -t stellar/stellar-horizon:dev
COPY --from=stellar/stellar-horizon:dev /horizon /usr/bin/stellar-horizon

RUN adduser --system --group --quiet --home /var/lib/stellar --disabled-password --shell /bin/bash stellar;

RUN ["mkdir", "-p", "/opt/stellar"]
RUN ["touch", "/opt/stellar/.docker-ephemeral"]

RUN ["ln", "-s", "/opt/stellar", "/stellar"]
RUN ["ln", "-s", "/opt/stellar/core/etc/stellar-core.cfg", "/stellar-core.cfg"]
RUN ["ln", "-s", "/opt/stellar/horizon/etc/horizon.env", "/horizon.env"]
ADD common /opt/stellar-default/common
ADD pubnet /opt/stellar-default/pubnet
ADD testnet /opt/stellar-default/testnet
ADD standalone /opt/stellar-default/standalone


ADD start /
RUN ["chmod", "+x", "start"]

ENTRYPOINT ["/start"]
