FROM rust AS builder

ARG REPO
ARG REF
WORKDIR /wd
RUN git clone ${REPO} /wd
RUN git fetch origin ${REF}
RUN git checkout ${REF}
RUN rustup show active-toolchain || rustup toolchain install
RUN cargo install stellar-xdr --features cli --path . --locked
