FROM node:22 AS builder

ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=9876
WORKDIR /lab
RUN git clone https://github.com/stellar/laboratory /lab
ARG NEXT_PUBLIC_COMMIT_HASH
RUN yarn install
RUN yarn build

EXPOSE 9876
CMD ["npm", "start"]
