FROM node:22 AS builder

ARG NEXT_PUBLIC_COMMIT_HASH
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=8002
WORKDIR /lab
RUN git clone https://github.com/stellar/laboratory /lab
RUN git fetch origin ${NEXT_PUBLIC_COMMIT_HASH}
RUN git checkout ${NEXT_PUBLIC_COMMIT_HASH}
RUN yarn install
ENV NEXT_PUBLIC_DEFAULT_NETWORK=custom
ENV NEXT_BASE_PATH=/lab
RUN yarn build

EXPOSE 8002
CMD ["npm", "start"]
