FROM golang:1.20.1 AS builder

ARG REF
WORKDIR /go/src/github.com/stellar/go
RUN git clone https://github.com/stellar/go /go/src/github.com/stellar/go
RUN git fetch origin ${REF}
RUN git checkout ${REF}
ENV CGO_ENABLED=0
ENV GOFLAGS="-ldflags=-X=github.com/stellar/go/support/app.version=${REF}-(built-from-source)"
RUN go install github.com/stellar/go/services/horizon
