ARG STELLAR_CORE_VERSION=19.5.1-1137.b3a6bc281.focal~soroban
ARG HORIZON_VERSION=2.22.0~soroban-318
ARG FRIENDBOT_VERSION=soroban-v0.0.2-alpha
ARG SOROBAN_RPC_VERSION=0.3.0-31

FROM golang:1.19 as go

ARG FRIENDBOT_VERSION

RUN go install github.com/stellar/go/services/friendbot@$FRIENDBOT_VERSION

FROM ubuntu:20.04

ARG STELLAR_CORE_VERSION
ARG HORIZON_VERSION
ARG SOROBAN_RPC_VERSION

EXPOSE 5432
EXPOSE 8000
EXPOSE 6060
EXPOSE 11625
EXPOSE 11626

ADD dependencies /
RUN ["chmod", "+x", "dependencies"]
RUN /dependencies

ADD install /
RUN ["chmod", "+x", "install"]
RUN /install
COPY --from=go /go/bin/friendbot /usr/local/bin/friendbot

RUN ["mkdir", "-p", "/opt/stellar"]
RUN ["touch", "/opt/stellar/.docker-ephemeral"]

RUN ["ln", "-s", "/opt/stellar", "/stellar"]
RUN ["ln", "-s", "/opt/stellar/core/etc/stellar-core.cfg", "/stellar-core.cfg"]
RUN ["ln", "-s", "/opt/stellar/horizon/etc/horizon.env", "/horizon.env"]
ADD common /opt/stellar-default/common
ADD pubnet /opt/stellar-default/pubnet
ADD testnet /opt/stellar-default/testnet
ADD standalone /opt/stellar-default/standalone
ADD futurenet /opt/stellar-default/futurenet


ADD start /
RUN ["chmod", "+x", "start"]

ENTRYPOINT ["/start"]
