name: 'Push'
inputs:
  head_sha:
    required: true
  artifact_name:
    required: true
  artifact_image_file:
    required: true
  image:
    required: true
    default: quickstart
  arch:
    required: true
  name:
    required: true
    default: ghcr.io/${{ github.repository }}:latest
  registry:
    required: true
    default: ghcr.io
  username:
    required: true
    default: ${{ github.actor }}
  password:
    required: true
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    -
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: /tmp/
    -
      shell: bash
      run: docker load -i /tmp/${{ inputs.artifact_image_file }}
    -
      shell: bash
      run: docker tag ${{ inputs.image }} ${{ inputs.name }}
    -
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    -
      shell: bash
      run: |
        docker push ${{ inputs.name }}
    -
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: '${{ inputs.head_sha }}',
            state: 'success',
            context: `${{ inputs.name }}`,
            description: 'Available',
          });
