# Deploy this Fly app with:
# fly launch --config .fly/fly.toml --copy-config --ha=false

[build]
image = "docker.io/stellar/quickstart:latest"

[env]
# NETWORK chooses the network the image will connect to. Use "local" to start a
# new network local to the container, ideal for development and testing.
NETWORK="local"

# LIMITS sets the network configuration that is deployed on network start.
# - "testnet" to match the network configuration of the public Stellar testnet.
# - "unlimited" raises limits to max, useful for testing prior to optimization.
#LIMITS="testnet"

# RANDOMIZE_NETWORK_PASSPHRASE sets a random network passphrase on network
# start. Find out what the network passphrase is by requesting the root URL.
#RANDOMIZE_NETWORK_PASSPHRASE="true"

# NETWORK_PASSPHRASE sets a network passphrase to uniquely identify the network
# and prevent use of transactions for the test network with other networks.
#NETWORK_PASSPHRASE="My Network"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1

[deploy]
strategy = "immediate"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
