#!/usr/bin/env python3

import json
import sys

# Accepts as stdin a JSON object in the format of images.json. Outputs an array
# of all the additional test cases defined in the images merged together.
# Usage: < images.json ./.scripts/images-additional-tests

images = json.load(sys.stdin)
tests = []
for image in images:
    tag = image['tag']
    for test in image.get('additional-tests', []):
        tests.append({'image': {'tag': tag}, **test})
    for test in image.get('tests', {}).get('additional-tests', []):
        tests.append({'image': {'tag': tag}, **test})

print(json.dumps(tests))
