#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"

# Accepts as stdin a JSON object in the format of images.json. Outputs an array
# of all dependencies that need to be built across all the images.
# Usage: < images.json ./.scripts/images-deps

images = JSON.parse($stdin.read)
deps = images.flat_map { |image| image["deps"] }.uniq
puts(JSON.generate(deps))
