#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"

# Accepts as stdin a JSON object in the format of images.json. Outputs an array
# of all the additional test cases defined in the images merged together.
# Usage: < images.json ./.scripts/images-additional-tests

images = JSON.parse($stdin.read)

tests = []
images.each do |image|
  image.fetch("additional-tests", []).each do |test|
    tests.push({ "image" => image }.merge(test))
  end
  image.fetch("tests", {}).fetch("additional-tests", []).each do |test|
    tests.push({ "image" => image }.merge(test))
  end
end

puts(JSON.generate(tests))
