#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "open3"
require "digest"

# Accepts as stdin a JSON object in the format of images.json.
# And adds some calculatble elements used during the build.
#
# 1. Resolves any 'ref' values in the JSON to a revision sha.
# 2. Hashes the entire dep details and injects the hash as an id into the deps
#    details. The id can be used to uniquely identify a dep configuration.
#
# Outputs the original JSON modified.
#
# Usage: < images.json ./.scripts/images-with-extras

images = JSON.parse($stdin.read)

cache = {}

images.each do |image|
  tag = image["tag"]
  image["deps"].each do |dep|
    name = dep["name"]
    repo = dep["repo"]
    ref = dep["ref"]
    warn("#{tag} #{name} #{repo} #{ref} ...")

    key = [name, repo, ref]
    if cache.key?(key)
      sha = cache[key]
    else
      stdout, stderr, status = Open3.capture3("gh", "api", "repos/#{repo}/commits/#{ref}", "--jq", ".sha")
      if !status.success?
        abort("Error: failed to get commit for #{repo}/#{ref}: #{stderr}")
      end
      sha = stdout.strip
      cache[key] = sha
    end
    warn(" • revision sha = #{sha}")
    dep["sha"] = sha

    dep_id = Digest::SHA256.hexdigest(JSON.generate(dep))
    dep["id"] = dep_id
    warn(" • id = #{dep_id}")
  end
end

puts(JSON.generate(images))
