name: Dockerfile

on:
  push:
  pull_request:

# Prevent more than one build of this workflow for a branch to be running at the
# same time, and if multiple are queued, only run the latest, cancelling any
# already running build. The exception being any protected branch, such as
# master, where a build for every commit will run.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_protected == 'true' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@5146db6c4d81fbfd508899f851bbb3883a96ff9f
    - name: Build Quickstart Image
      run: docker buildx build -f Dockerfile -t stellar/quickstart --label org.opencontainers.image.revision="${{ github.sha }}" -o type=docker,dest=/tmp/image .
    - name: Upload Quickstart Image
      uses: actions/upload-artifact@v2
      with:
        name: image-Dockerfile
        path: /tmp/image

  test:
    if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/master' }}
    needs: build
    strategy:
      matrix:
        network: [testnet, pubnet, standalone]
        options: ["", --enable-horizon-captive-core]
        exclude:
          - network: testnet
            options: --enable-horizon-captive-core
          - network: pubnet
            options: --enable-horizon-captive-core
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download Quickstart Image
      uses: actions/download-artifact@v2
      with:
        name: image-Dockerfile
        path: /tmp/
    - name: Load Quickstart Image
      run: docker load -i /tmp/image
    - name: Run Quickstart Image
      run: docker run --rm -d -p "8000:8000" --name stellar stellar/quickstart --${{ matrix.network }} ${{ matrix.options }}
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1
    - name: Sleep until supervisor is up
      run: sleep 10
    - name: Run test
      run: |
        echo "supervisorctl tail -f stellar-core" | docker exec -i stellar sh &
        echo "supervisorctl tail -f horizon" | docker exec -i stellar sh &
        go run test.go
        curl http://localhost:8000

  push:
    if: ${{ github.event_name == 'push' }}
    needs: build
    permissions:
      packages: write
      statuses: write
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
      IMAGE_REPO: ghcr.io/${{ github.event.pull_request.head.repo.full_name || github.repository }}
      # IMAGE_REPO: docker.io/stellar/quickstart
    steps:
    - name: Download Quickstart Image
      uses: actions/download-artifact@v2
      with:
        name: image-Dockerfile
        path: /tmp/
    - name: Load Quickstart Image
      run: docker load -i /tmp/image
    - name: Log in to ghcr.io
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # - name: Log in to docker.io
    #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
    #   with:
    #     registry: docker.io
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set Env Vars
      run: |
        echo "COMMIT_SHORT_SHA=${COMMIT_SHA::7}" >> $GITHUB_ENV
        echo "IMAGE_SHA256=$(docker inspect --format='{{.ID}}' stellar/quickstart)" >> $GITHUB_ENV
    - name: Push Quickstart Image
      run: |
        IMAGE_ID=$IMAGE_REPO:$COMMIT_SHORT_SHA
        docker tag stellar/quickstart $IMAGE_ID
        docker push $IMAGE_ID
    - uses: actions/github-script@v5
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: '${{ env.COMMIT_SHA }}',
            state: 'success',
            context: context.workflow,
            description: '${{ env.IMAGE_REPO }}@${{ env.IMAGE_SHA256 }}',
          });

  tag:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs: [push, test]
    permissions:
      packages: write
      statuses: write
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: ghcr.io/${{ github.event.pull_request.head.repo.full_name || github.repository }}
      # IMAGE_REPO: docker.io/stellar/quickstart
      IMAGE_TAG: latest
    steps:
    - name: Download Quickstart Image
      uses: actions/download-artifact@v2
      with:
        name: image-Dockerfile
        path: /tmp/
    - name: Load Quickstart Image
      run: docker load -i /tmp/image
    - name: Log in to ghcr.io
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # - name: Log in to docker.io
    #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
    #   with:
    #     registry: docker.io
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Quickstart Image
      run: |
        IMAGE_ID=$IMAGE_REPO:$IMAGE_TAG
        docker tag stellar/quickstart $IMAGE_ID
        docker push $IMAGE_ID
    - uses: actions/github-script@v5
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: '${{ env.COMMIT_SHA }}',
            state: 'success',
            context: context.workflow,
            description: '${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}',
          });
