name: Update Config Settings Test

on:
  pull_request:
  push:
    branches: [main]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install stellar-cli
      uses: stellar/stellar-cli@v26.1.0

    - name: Run update-config-settings
      id: update
      run: |
        file="$(./.scripts/update-config-settings)"
        echo "file=$file" >> "$GITHUB_OUTPUT"

    - name: Validate ConfigUpgradeSet
      run: stellar xdr encode --type ConfigUpgradeSet < "${{ steps.update.outputs.file }}" > /dev/null
