name: Workflow Call Test

on:
  push:

jobs:

  build-custom:
    uses: ./.github/workflows/build.yml
    with:
      sha: ${{ github.event.pull_request.head.sha || github.sha }}
      test: true
      image_json: |
        {
          "tag": "custom",
          "config": {
            "protocol_version_default": 23
          },
          "deps": [
            { "name": "xdr", "repo": "stellar/rs-stellar-xdr", "ref": "v23.0.0" },
            { "name": "core", "repo": "stellar/stellar-core", "ref": "v23.0.1", "options": { "configure_flags": "--disable-tests" } },
            { "name": "rpc", "repo": "stellar/stellar-rpc", "ref": "v23.0.1" },
            { "name": "horizon", "repo": "stellar/go", "ref": "horizon-v23.0.0" },
            { "name": "friendbot", "repo": "stellar/go", "ref": "horizon-v23.0.0" },
            { "name": "lab", "repo": "stellar/laboratory", "ref": "main" }
          ],
          "additional-tests": []
        }

  use-custom:
    needs: build-custom
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build-custom.outputs.image_artifact
        path: /tmp/
    - run: docker load -i /tmp/image
    - run: >
        docker run
        --platform linux/amd64
        -d
        -p
        "8000:8000"
        --name stellar
        quickstart
        --local
    - run: sleep 10
    - run: curl http://localhost:8000
